// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsqffjgmqqgneczrkrpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzcWZmamdtcXFnbmVjenJrcnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3OTY2NTEsImV4cCI6MjA3NjM3MjY1MX0.EDO4Ymndr4c7Z5SIoV4i1WzFb9BVkujBCc3yu6GdwS4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});